name: Add issues to OT & Data Engineering Portfolio

on:
  issues:
    types:
      - opened
      - reopened
      - transferred

jobs:
  add-to-project:
    name: Add issue to portfolio
    runs-on: ubuntu-latest

    steps:
      - name: Add issue to project
        uses: actions/add-to-project@v2
        with:
          project-url: https://github.com/users/brewmateot/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
